name: CI

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Git LFS
      run: |
        git lfs install
        git lfs pull

    - name: Set up Python 3.11.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare environment
      run: |
        python app/prepare_scaler_and_model.py

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        if [ -n "$(git status --porcelain=data/scaler.pkl)" ] || [ -n "$(git status --porcelain=data/model.pkl)" ]; then
          git add data/scaler.pkl data/model.pkl
          git commit -m "Update scaler and model [skip ci]"
          git push
        else
          echo "scaler.pkl et model.pkl inchangés."
        fi

    - name: Delete hooks
      run: |
        if [ -f .git/hooks/pre-push ]; then
          rm .git/hooks/pre-push
          git commit -m "Delete heroku hooks [CI]" --allow-empty
          git push
        else
          echo "No pre-push hook to delete."
        fi

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.13.15
      with:
        heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
        heroku_app_name:  ${{secrets.HEROKU_API_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}     

#      env:
#        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
#        HEROKU_APP_NAME: ${{ secrets.HEROKU_API_NAME }}
#      if: github.ref == 'refs/heads/main' && job.status == 'success'
#      run: |
#        git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
#        git push heroku HEAD:main -f

#      env:
#        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
#        HEROKU_APP_NAME: ${{ secrets.HEROKU_API_NAME }} 
#      run: |
#        git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_API_NAME.git
#        git push heroku `git subtree split --prefix app main`:main --force