name: CI

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Git LFS
      run: |
        git lfs install
        git lfs pull

    - name: Set up Python 3.11.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare environment
      run: |
        python app/prepare_scaler_and_model.py

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add data/scaler.pkl data/model.pkl
        git commit -m "Update scaler and model [skip ci]"
        git push

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_API_NAME }} 
      run: |
        git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_API_NAME.git
        # git remote add heroku https://git.heroku.com/failurerepay.git
        git push heroku `git subtree split --prefix app main`:main --force