name: CI

on:
  push:
    branches:
      - new-main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare environment
      run: |
        python prepare_environment.py

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add data/scaler.pkl data/model.pkl
        git commit -m "Update scaler and model [skip ci]"
        git push
