name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mlflow:
        image: mlflow/mlflow
        ports:
          - 5001:5001
        options: --name mlflow-server

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install Flask-Testing

    - name: Run tests
      env:
        MLFLOW_TRACKING_URI: http://localhost:5001
      run: |
        mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0 --port 5001 &
        sleep 10  # Attendre que le serveur MLflow démarre
        python -m unittest discover -s tests